{% set version = "1.5.0" %}

package:
  name: ucc
  version: {{ version }}

source:
  url: https://github.com/openucx/ucc/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 7ab61a3215616ee9a7a6f51e61cfaac9e7055a12b233aef8d4a7218d2cb3860f

build:
  skip: true  # [not linux]
  skip: true  # [cuda_compiler_version not in ("12.9")]
  number: 0
  run_exports:
    - {{ pin_subpackage("ucc") }}
  missing_dso_whitelist:
    - '*libcuda.so*'
    - '*libcudart.so*'
    - '*libnvidia-ml.so*'
    - '*libnccl.so*'
  ignore_run_exports_from:
    # CXX standard library is unused
    - {{ compiler('cxx') }}
    # allow CPU-only use cases (xref: conda-forge/ucx-split-feedstock#173)
    - {{ compiler("cuda") }}
    - cuda-cudart-dev  # [(cuda_compiler_version or "None").startswith("12") and linux and x86_64]
    - nccl  # [linux and x86_64]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}
    - automake
    - autoconf !=2.72  # work around conda-forge/autoconf-feedstock#41
    - libtool
    - make
  host:
    - ucx
    - cuda-version {{ cuda_compiler_version }}
    - cuda-cudart-dev  # [(cuda_compiler_version or "None").startswith("12") and linux and x86_64]
    - cuda-nvml-dev    # [(cuda_compiler_version or "None").startswith("12") and linux and x86_64]
    - nccl
  run:
    - {{ pin_compatible("ucx", max_pin="x.x.x") }}
  run_constrained:
    - {{ pin_compatible("cuda-version", min_pin="x", max_pin="x") }}
    # The actual version constraint comes from cuda-version, so below we explicit list
    # them only to codify that these are expected (but optional) dependencies when CUDA
    # is in use, otherwise the solver gets confused (conda-forge/ucc-feedstock#19).
    - cudatoolkit                                               # [cuda_compiler == "nvcc"]
    - cuda-cudart                                               # [cuda_compiler == "cuda-nvcc"]
    - {{ pin_compatible("nccl", max_pin="x") }}

test:
  commands:
    - test -f $PREFIX/bin/ucc_info
    - test -f $PREFIX/include/ucc/api/ucc_def.h
    - test -f $PREFIX/include/ucc/api/ucc_status.h
    - test -f $PREFIX/include/ucc/api/ucc_version.h
    - test -f $PREFIX/include/ucc/api/ucc.h
    - test -f $PREFIX/lib/cmake/ucc/ucc-targets.cmake
    - test -f $PREFIX/lib/cmake/ucc/ucc-config-version.cmake
    - test -f $PREFIX/lib/cmake/ucc/ucc-config.cmake
    - test -f $PREFIX/lib/libucc.so.1
    - test -f $PREFIX/lib/ucc/libucc_mc_cuda.so.1
    - test -f $PREFIX/lib/ucc/libucc_mc_cpu.so.1
    - test -f $PREFIX/lib/ucc/libucc_tl_self.so.1
    - test -f $PREFIX/lib/ucc/libucc_tl_ucp.so.1
    - test -f $PREFIX/lib/ucc/libucc_cl_basic.so.1
    - test -f $PREFIX/lib/ucc/libucc_cl_hier.so.1
    - test -f $PREFIX/lib/ucc/libucc_ec_cuda.so.1
    - test -f $PREFIX/lib/ucc/libucc_ec_cpu.so.1
    - test -f $PREFIX/bin/.ucc-post-link.sh


about:
  home: https://github.com/openucx/ucc
  summary: 'UCC is a collective communication operations API and library.'
  description: |
    UCC is a collective communication operations API and library that is
    flexible, complete, and feature-rich for current and emerging
    programming models and runtimes.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - marcinz
    - m3vaz
    - sandeepd-nv
    - leofang
